version: '3.8'

services:
  main-domain-ui:
    image: main-domain:test
    container_name: main-domain
    networks:
      - enterprice-sedfiles
    ports:
      - "3000:3000"
    volumes:
      - main-domain-ui_data:/app/data
    env_file:
      - ../Frontend/.env.test

volumes:
  main-domain-ui_data:


networks:
  enterprice-sedfiles:
    driver: bridge
