version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ../nginx/test:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - enterprice-sedfiles
    restart: always

networks:
  enterprice-sedfiles:
    driver: bridge
