
version: '3.8'

services:
  auth-service:
    image: 
    container_name: auth-service
    networks:
      - sos
    ports:
      - "8000:8000"
    volumes:
      - auth-service_data:/app/data
    env_file:
      - ../Backend/.env.test

  core-service:
    image: 
    container_name: core-service
    networks:
      - 
    ports:
      - "8001:8001"
    volumes:
      - core-service_data:/app/data
    env_file:
      - ../Backend/.env.test
  sub-service:
    image: 
    container_name: sub-service
    networks:
      - 
    ports:
      - "8002:8002"
    volumes:
      - sub-service_data:/app/data
    env_file:
      - ../Backend/.env.test

volumes:
  core-service_data:
  auth-service_data:
  sub-service_data:


networks:
  sos:
    driver: bridge
